#!/bin/bash

# Upload the ClinVar-GKS monthly FULL bundle from local disk to Cloudflare R2.
# Runs after export-gks-dicts.sh + assemble-gks-dicts.py have produced the bundle.
#
# As of Plan 4 the full bundle is published MONTH-END ONLY (retroactively, for the
# last release of a month). Weekly publishing moved to the delta product
# (upload-gks-delta-to-r2.sh → deltas/). This script now manages only:
#   datasets/                  — monthly full bundles for the current year + 00-latest
#   datasets/parquet/          — per-section Parquet for the current monthly full
#   archives/{yyyy}/           — monthly files rolled over from prior years
#   README.txt                 — bucket overview
#
# The passed bundle is published UNCONDITIONALLY to the monthly slot. Boundary
# detection now governs only year-rollover archiving: if the newest monthly already
# in datasets/ is from a prior year, its year's monthlies are moved to archives/{yyyy}/
# before the new upload. index.json is regenerated by generate-r2-index.sh.
#
# Usage:
#   ./upload-gks-to-r2.sh <export_date> <dataset_version> <bundle_file> [--dry-run] [--parquet-dir=DIR]
#
# Examples:
#   ./upload-gks-to-r2.sh 2026-06-27 v2_5_0 /tmp/clinvar-gks-2026-06-27.json.gz
#   ./upload-gks-to-r2.sh 2026-06-27 v2_5_0 /tmp/clinvar-gks-2026-06-27.json.gz --dry-run

set -e

# --- Positional arguments ---
if [[ $# -lt 3 ]]; then
  echo "Usage: $0 <export_date> <dataset_version> <bundle_file> [--dry-run] [--parquet-dir=DIR]"
  echo "  export_date      ClinVar release date (YYYY-MM-DD)"
  echo "  dataset_version  Dataset version (e.g. v2_5_0)"
  echo "  bundle_file      Local path to the assembled bundle (.json.gz)"
  exit 1
fi

EXPORT_DATE="$1"
DATASET_VERSION="$2"
BUNDLE_FILE="$3"
shift 3

# Validate date format
if ! [[ "$EXPORT_DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
  echo "ERROR: export_date must be YYYY-MM-DD format, got '${EXPORT_DATE}'"
  exit 1
fi

# --- Parse flags ---
DRY_RUN=false
PARQUET_DIR=""
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --parquet-dir=*) PARQUET_DIR="${arg#--parquet-dir=}" ;;
    *)
      echo "ERROR: Unknown argument '${arg}'"
      echo "Usage: $0 <export_date> <dataset_version> <bundle_file> [--dry-run] [--parquet-dir=DIR]"
      exit 1
      ;;
  esac
done

# --- R2 Configuration ---
R2_ACCOUNT_ID="09208aa33790838db213a21f630c33e7"
R2_BUCKET="clinvar-gks"
R2_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
R2_PROFILE="r2"
R2_PUBLIC_URL="https://pub-9c5470edadb8496fb0abbf396291660b.r2.dev"

# --- Derived date components ---
YEAR="${EXPORT_DATE:0:4}"
MM="${EXPORT_DATE:5:2}"

# --- Filenames ---
MONTHLY_FILE="clinvar-gks_${YEAR}-${MM}.json.gz"
LATEST_MONTHLY="clinvar-gks_00-latest.json.gz"

# --- Locate script directory for r2-readme.txt + generate-r2-index.sh ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# =====================================================================
# Helper functions
# =====================================================================

r2_upload() {
  local src="$1" dest="$2" content_type="${3:-application/gzip}"
  if $DRY_RUN; then
    echo "  [dry-run] upload: ${dest}"
    return
  fi
  aws s3 cp "$src" "s3://${R2_BUCKET}/${dest}" \
    --endpoint-url "${R2_ENDPOINT}" \
    --profile "${R2_PROFILE}" \
    --content-type "${content_type}" \
    --quiet
}

r2_copy() {
  local src="$1" dest="$2"
  if $DRY_RUN; then
    echo "  [dry-run] copy: ${src} -> ${dest}"
    return
  fi
  aws s3 cp "s3://${R2_BUCKET}/${src}" "s3://${R2_BUCKET}/${dest}" \
    --endpoint-url "${R2_ENDPOINT}" \
    --profile "${R2_PROFILE}" \
    --quiet
}

r2_ls() {
  local prefix="$1"
  aws s3 ls "s3://${R2_BUCKET}/${prefix}" \
    --endpoint-url "${R2_ENDPOINT}" \
    --profile "${R2_PROFILE}" \
    2>/dev/null | awk '{print $NF}' || true
}

r2_rm() {
  local key="$1"
  if $DRY_RUN; then
    echo "  [dry-run] delete: ${key}"
    return
  fi
  aws s3 rm "s3://${R2_BUCKET}/${key}" \
    --endpoint-url "${R2_ENDPOINT}" \
    --profile "${R2_PROFILE}" \
    --quiet
}

# =====================================================================
# Year-rollover detection (the only boundary this uploader still governs)
# =====================================================================

detect_boundaries() {
  # List existing dated monthly files (exclude 00-latest) and find the newest year.
  # If it differs from the release year, we archive the prior year before uploading.
  EXISTING_MONTHLY_FILES=()
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    [[ "$f" == *"00-latest"* ]] && continue
    [[ "$f" =~ ^clinvar-gks_[0-9]{4}-[0-9]{2}\.json\.gz$ ]] || continue
    EXISTING_MONTHLY_FILES+=("$f")
  done < <(r2_ls "datasets/clinvar-gks_")

  IS_NEW_YEAR=false
  PREV_YEAR=""

  local newest=""
  for f in "${EXISTING_MONTHLY_FILES[@]}"; do
    # clinvar-gks_2026-06.json.gz -> newest lexical filename == newest year-month
    if [[ -z "$newest" || "$f" > "$newest" ]]; then
      newest="$f"
    fi
  done

  if [[ -n "$newest" ]]; then
    local date_part="${newest#clinvar-gks_}"   # 2026-06.json.gz
    PREV_YEAR="${date_part:0:4}"               # 2026
    if [[ "$YEAR" != "$PREV_YEAR" ]]; then
      IS_NEW_YEAR=true
    fi
  fi
}

# =====================================================================
# Archive operations
# =====================================================================

archive_yearly() {
  # Move dated monthly files from datasets/ to archives/{prev_year}/.
  # LATEST_MONTHLY is retained; it gets overwritten by the new upload below.
  echo "--- Year rollover: archiving ${PREV_YEAR} monthly files to archives/${PREV_YEAR}/ ---"

  local monthly_files=()
  while IFS= read -r f; do
    [[ -n "$f" ]] && monthly_files+=("$f")
  done < <(r2_ls "datasets/clinvar-gks_" | grep -v "00-latest" || true)

  for f in "${monthly_files[@]}"; do
    echo "  Moving datasets/${f} -> archives/${PREV_YEAR}/${f}"
    r2_copy "datasets/${f}" "archives/${PREV_YEAR}/${f}"
    r2_rm "datasets/${f}"
  done
}

upload_parquet() {
  local parquet_dir="$1"
  if [[ -z "$parquet_dir" || ! -d "$parquet_dir" ]]; then
    echo "  (no Parquet dir found, skipping)"
    return
  fi

  echo "--- Uploading Parquet section files ---"
  local uploaded=0
  for parquet_file in "${parquet_dir}"/*.parquet; do
    [[ -f "$parquet_file" ]] || continue
    local section
    section="$(basename "${parquet_file}" .parquet)"
    echo "  datasets/parquet/${section}.parquet"
    r2_upload \
      "${parquet_file}" \
      "datasets/parquet/${section}.parquet" \
      "application/vnd.apache.parquet"
    (( uploaded++ )) || true
  done
  echo "  ${uploaded} Parquet files uploaded."
}

publish_monthly() {
  # Publish the passed bundle directly to the monthly slot + latest.
  echo "--- Publishing monthly FULL ---"
  echo "  Monthly:  datasets/${MONTHLY_FILE}"
  r2_upload "${BUNDLE_FILE}" "datasets/${MONTHLY_FILE}"
  echo "  Latest:   datasets/${LATEST_MONTHLY}"
  r2_upload "${BUNDLE_FILE}" "datasets/${LATEST_MONTHLY}"
}

# =====================================================================
# Main
# =====================================================================

echo "=== ClinVar-GKS Monthly FULL Upload ==="
echo "  Release date:  ${EXPORT_DATE}"
echo "  Version:       ${DATASET_VERSION}"
echo "  Monthly file:  ${MONTHLY_FILE}"
if $DRY_RUN; then
  echo "  Mode:          DRY RUN"
fi
echo ""

# --- Check bundle file ---
echo "Checking bundle: ${BUNDLE_FILE}"
if ! $DRY_RUN && [[ ! -f "${BUNDLE_FILE}" ]]; then
  echo "ERROR: Bundle file not found at ${BUNDLE_FILE}"
  echo "  Run export-gks-dicts.sh and assemble-gks-dicts.py first."
  exit 1
fi

# --- Detect year rollover (archive prior-year monthlies before publishing) ---
echo ""
echo "Detecting year rollover..."
detect_boundaries
echo "  New year:  ${IS_NEW_YEAR}"
echo ""

if $IS_NEW_YEAR; then
  archive_yearly
  echo ""
fi

# --- Publish the monthly full (unconditional) ---
publish_monthly
echo ""

# --- Upload Parquet files (if generated) ---
if [[ -n "${PARQUET_DIR}" ]]; then
  upload_parquet "${PARQUET_DIR}"
  echo ""
fi

# --- Upload README.txt ---
README_SRC="${SCRIPT_DIR}/r2-readme.txt"
if [[ -f "${README_SRC}" ]]; then
  echo "Uploading README.txt"
  r2_upload "${README_SRC}" "README.txt" "text/plain"
  echo ""
fi

# --- Regenerate index.json (shared generator) ---
INDEX_ARGS=()
$DRY_RUN && INDEX_ARGS+=("--dry-run")
"${SCRIPT_DIR}/generate-r2-index.sh" "${INDEX_ARGS[@]}"

# --- Summary ---
echo ""
echo "=== Upload Complete ==="
echo "  Monthly: ${R2_PUBLIC_URL}/datasets/${MONTHLY_FILE}"
echo "  Latest:  ${R2_PUBLIC_URL}/datasets/${LATEST_MONTHLY}"
if [[ -n "${PARQUET_DIR}" && -d "${PARQUET_DIR}" ]]; then
  echo "  Parquet: ${R2_PUBLIC_URL}/datasets/parquet/"
fi
echo "  Index:   ${R2_PUBLIC_URL}/index.json"
